[package]
name = "riscv_asm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# crate_type = ["staticlib"]

[dependencies]
# cc = "1.0.79"

[workspace]